---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by draycia.
--- DateTime: 10/24/19 4:16 PM
---

local Summoner = {}

-- https://developer.riotgames.com/apis#summoner-v4/GET_getByAccountId
function Summoner.by_account(encrypted_account_id)
    return api_client.api_call(
            "GET",
            "https://na1.api.riotgames.com/lol/summoner/v4/summoners/by-account/" .. encrypted_account_id
    );
end

-- https://developer.riotgames.com/apis#summoner-v4/GET_getBySummonerName
function Summoner.by_name(summoner_name)
    return api_client.api_call(
            "GET",
            "https://na1.api.riotgames.com/lol/summoner/v4/summoners/by-name/" .. urlencode(summoner_name)
    );
end

-- https://developer.riotgames.com/apis#summoner-v4/GET_getByPUUID
function Summoner.by_puuid(encrypted_puuid)
    return api_client.api_call(
            "GET",
            "https://na1.api.riotgames.com/lol/summoner/v4/summoners/by-puuid/" .. encrypted_puuid
    );
end

-- https://developer.riotgames.com/apis#summoner-v4/GET_getBySummonerId
function Summoner.by_id(id)
    return api_client.api_call(
            "GET",
            "https://na1.api.riotgames.com/lol/summoner/v4/summoners/" .. id
    );
end

return Summoner