---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by draycia.
--- DateTime: 10/24/19 4:11 PM
---

api_client = require("api-client");
api_key = arg[1];

local Summoner = require("v4.Summoner");
local ThirdPartyCode = require("v4.ThirdPartyCode");

-- Tests:
local summonerId = Summoner.by_name("Vìcarious").id;
print(ThirdPartyCode.by_summoner(summonerId));
